### PR TITLE
Fix param read loop for python 3

### PR DESCRIPTION
**Pull request by tpwrules**
This commit changes the 'blank parameter ID' value from empty string to empty bytes, so that it can be packed for transmission to the copter in Python 3.

### CODE REVIEW

**Comment by pietrodn** [comment]
I think this should be fixed in pymavlink rather than in DroneKit: the correct type for a parameter name should be a `str`, not `bytes`.
I already submitted a PR in pymavlink which would fix this error: https://github.com/ArduPilot/pymavlink/pull/141

**Comment by amilcarlucas** [comment]
There have been some recent changes on pymavlink regarding this. Can you retest?

**Comment by pietrodn** [comment]
The first commit is OK as the `param_request_read_send` [accepts a byte string](https://github.com/ArduPilot/pymavlink/blob/670cc9a786666e0e7931f93c36242e45d0554ca2/mavutil.py#L412) as the third argument.
The second commit is unrelated and should be stripped from the PR.

**Comment by pietrodn** [comment]
This can be closed in favor of #865, as this contains an unrelated change and needs a rebase.

**Comment by amilcarlucas** [comment]
@peterbarker ardupilot/pymavlink#865 has been merged, so this one can be closed now

**Pull request closed without merging**
