### PR TITLE
Make running dronekit examples possible in Vagrant

### PR DESCRIPTION
**Pull request by peterbarker**
Add some extra packages.
Create a private network to host machine

### CODE REVIEW

**Comment by mrpollo** [comment]
@peterbarker same story, can you rebase please?

**Comment by peterbarker** [comment]
On Tue, 12 Apr 2016, Ramon Roche wrote:

> @peterbarker same story, can you rebase please?

Rebased.

**Comment by hamishwillee** [comment]
@peterbarker This doesn't think it is rebased - perhaps broken by another merge?

**Comment by peterbarker** [comment]
On Tue, 12 Apr 2016, Hamish Willee wrote:

> @peterbarker This doesn't think it is rebased - perhaps broken by another
> merge?

Like the one you just did? :-)

Rebased again.

**Comment by hamishwillee** [comment]
@peterbarker I accept full responsibility. Let us never talk of this again.

**Pull request merged**
