### PR TITLE
MAVConnection: stop threads on exit and connection close

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
See issue #645 - misleading and distracting exits from dkpy cause support issues.

**Comment by hamishwillee** [comment]
Looks sane to me, but I'm not planning on testing this. Did you get feedback from people reporting the original problem?

**Comment by peterbarker** [comment]
On Sun, 17 Jul 2016, Hamish Willee wrote:

> Looks sane to me, but I'm not planning on testing this. Did you get feedback
> from people reporting the original problem?

Yes, I think the issue I referenced included a comment from someone saying 
it seemed to fix the problem for them.

**Comment by franknitty69** [comment]
i tested the fix as well and can confirm that dronekit-python scripts now exit gracefully.

**Comment by hamishwillee** [comment]
I have merged this then :-) @peterbarker or @mrpollo do you have time for a re-release with this change?

**Comment by mrpollo** [comment]
thanks @peterbarker, I'll cut a new release

**Comment by hamishwillee** [comment]
Thanks guys.

**Pull request merged**
