### PR TITLE
Improved MAVLink message example and guide #277

### PR DESCRIPTION
**Pull request by hamishwillee**
@tcr3dr @mrpollo So this moves the set_mavlink_callback docs out of the vehicle_state guide and into its own guide doc. In addition it adds a (pretty cool :-) ) example and docs of how to add your own attributes to the Vehicle class in a script. 

Unlike the other examples, the example doc has quite a lot of explanation - I decided that in this case it made sense because it extends the callback functionality. I have linked to it from the guide though.

Let me know what you think.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@tcr3dr Can we merge this please.

**Comment by mrpollo** [comment]
you might need to rebase @hamishwillee 

@tcr3dr whats up with CircleCI?

**Comment by hamishwillee** [comment]
@mrpollo @tcr3dr Rebased. Please integrate.

**Comment by hamishwillee** [comment]
Closing this one. Doing some fixes and will reopen.

**Pull request closed without merging**
