### PR TITLE
v1.4.1

### PR DESCRIPTION
**Pull request by tcr3dr**
See release notes for details.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@tcr3dr Any idea when this likely to go live? 2 hours is a long wait isn't it?

**Comment by tcr3dr** [comment]
@hamishwillee Should have worked... https://pypi.python.org/pypi/droneapi/1.4.1

**Comment by hamishwillee** [comment]
Ah, I mean that the docs build is still on 1.3.1 - this is just PIP? http://python.dronekit.io/about/release_notes.html

**Comment by tcr3dr** [comment]
Got it, should be updated now. http://python.dronekit.io/about/release_notes.html

**Comment by hamishwillee** [comment]
Yes- updated thanks:

* Did anything have to be pushed or was it just a matter of waiting? I ask so that I know how long I should be patient for before nagging.
* I'm having to refresh my local cache on every page to get these to display - can we somehow force a cache refresh?

**Comment by tcr3dr** [comment]
@hamishwillee That was all on me, I forgot that step. And It's just a one-liner, so not a problem at all to ping me on it.

Let me look into cache refreshing, I need to familiarize myself with the hosting we use...

**Comment by hamishwillee** [comment]
@tcr3dr Not a worry - but you'll never get back that carefully cultivated aura of infallibility :-) Thanks for the information.

**Comment by tcr3dr** [comment]
The reality:

**Comment by hamishwillee** [comment]
+1 :-)

**Pull request merged**
