### PR TITLE
Windows Installer: add/removes module load droneapi.module.api

### PR DESCRIPTION
**Pull request by stephendade**
For #267.

The Windows installer will now automatically add "module load droneapi.module.api" to mavinit.scr during the installation and remove the line upon uninstallation.

### CODE REVIEW

**Comment by tcr3dr** [comment]
Hey @stephendade, thanks for the PR. Can you rebase over master branch? This should fix the failing tests on the latest PRs.

**Comment by stephendade** [comment]
@tcr3dr - should be all up-to-date now!

**Comment by tcr3dr** [comment]
As it turns out, we'll no longer need this with ActivePython. I'm going to close this and hope we can move fast enough to make up for lost time.

**Comment by hamishwillee** [comment]
@tcr3dr  I think you mean "now that we don't depend on MAVProxy". Sleepy?

@stephendade Thanks so much for your support of DroneKit with features like this - made things much easier for our users, and for me personally. If you feel inclined, feel free to add DKPY back into MAVPRoxy :-)

**Pull request closed without merging**
