### PR TITLE
Implements waypoints in DKPY2.

### PR DESCRIPTION
**Pull request by tcr3dr**
This also removes some deprecated properties (RC, __param), redirecting them to the module object.

### CODE REVIEW

**Comment by tcr3dr** [comment]
Review? @mrpollo

**Comment by mrpollo** [comment]
lgtm

**Note**: rc is coming back in before we release 2.0 stable

**Comment by hamishwillee** [comment]
#335 adds the rc-override code/docs back as a "standalone" example (untested).

@tcr3dr does this put Home in a separate attributed as per #207?

**Comment by tcr3dr** [comment]
@hamishwillee It doesn't; I'm still ensuring we have compatibility with existing code before we switch over to API changes.

**Comment by hamishwillee** [comment]
Thanks for clarification.

**Pull request merged**
