### PR TITLE
an example was using vehicle.gimbal without checking if it's valid fi…

### PR DESCRIPTION
**Pull request by davidbuzz**
…rst.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@davidbuzz Thanks for this. Traditionally we've assumed existence - ie the examples reflect the head revision of DK-Python. I'm not sure whether that is better, or checking as you have done.

**Comment by peterbarker** [comment]
@davidbuzz Thanks for the PR, but I'm with Hamish on this one.

The examples are in the same repo as the code; I believe it is reasonable for them to reflect the code in the checkout with them, and that adding checks to all of the examples based on differences between older and newer versions would unnecessarily clutter the example code.

I'm curious to know how you came across this problem.  I'm guessing you had an install, but were running the examples from an updated git repo?

If you can make a strong use case, we're happy to reconsider :-)

Again, thanks.

**Comment by davidbuzz** [comment]
FYI:  I did nothing special, I just didn't have a gimbal attached, and the code appeared to assume that a gimbal would always be attached.

**Comment by hamishwillee** [comment]
All attributes return `None` if an attribute is not supported. From this example point of view there is no need to test for gimbal support.

**Pull request closed without merging**
