### PR TITLE
#610: Wrap iterable call in try..except to deal with unrecognised vehicle codes

### PR DESCRIPTION
**Pull request by fnoop**
Mode code isn't always in the mode mappings - for example mode 0 that GCS seem to use.  Handle the exception and return a false which seems to be logically correct return in this case.

### CODE REVIEW

**Comment by mrpollo** [comment]
excellent contribution, would you have time to add integration tests?

**Comment by fnoop** [comment]
@mrpollo - Hi, I'm brand new to git development so haven't got a clue I'm afraid.  But I'd like to learn and give it a go, if you could point me in the right direction?  Even just an existing example I can look at?

**Comment by mrpollo** [comment]
sure thing @fnoop 

take a look at the tests we have here https://github.com/dronekit/dronekit-python/tree/master/dronekit/test/sitl

**Comment by fnoop** [comment]
Note: The problem isn't that the mode code isn't in the mode mappings, it's that the mode mappings aren't created for all vehicle types, so _mode_mapping_bynumber() returns None for certain or unrecognised vehicle types (eg GCS).  Thus _is_mode_available() then fails doing a lookup against a None where it's expecting a Dict.
The fix is probably still correct, I think.

**Comment by fnoop** [comment]
@mrpollo added a test that triggers the bug and fails in the current master, but passes after this PR is applied

**Comment by mrpollo** [comment]
thanks for the clarification @fnoop I'm going to go ahead and merge, great work

**Pull request merged**
