### PR TITLE
Improve documentation now we can unset notification for raw mavlink m…

### PR DESCRIPTION
**Pull request by hamishwillee**
…essages

### CODE REVIEW

**Comment by tcr3dr** [comment]
This looks great! I'll investigate the CI issue and get this merged.

**Comment by tcr3dr** [comment]
Blocked by #246, silly me

**Comment by tcr3dr** [comment]
Taken care of by #248.

**Comment by hamishwillee** [comment]
@tcr3dr Did this go out in the current version? I can't see any docs for unset_mavlink_callback

**Pull request closed without merging**
