### PR TITLE
Reorder instructions in quickstart guide

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by hamishwillee** [comment]
@peterbarker I prefer the original order - works perfectly on Windows. Windows is for Winners. Linux is for ...

**Comment by hamishwillee** [comment]
But not enough to block it if you feel strongly  ....

**Comment by peterbarker** [comment]
User testing is priceless.  And he was working on Mac, so considered a neutral third party :-P

**Comment by hamishwillee** [comment]
Fair enough. Lets see if you can get the tests to pass :-)

**Comment by peterbarker** [comment]
@hamishwillee In the words of a wise man; 2 out-of-3 aint bad.

AppVeyor is no longer "Required", and I don't think this could reasonably affect anything it tests...

**Comment by hamishwillee** [comment]
@peterbarker Agree but 

1. Can you rebase?
2. Normally we can't merge if test fails ... so happy enough to merge, but how do I bypass appveyor to do so?

**Comment by hamishwillee** [comment]
@peterbarker Rebase?

**Comment by mrpollo** [comment]
@peterbarker we need to merge this, if you have time can you rebase so I can merge?

**Comment by peterbarker** [comment]
On Tue, 12 Apr 2016, Ramon Roche wrote:

> @peterbarker we need to merge this, if you have time can you rebase so I can
> merge?

Rebased.

**Comment by hamishwillee** [comment]
Thanks @peterbarker - LGTM

**Pull request merged**
