### PR TITLE
Replaces public instances of dronekit.lib with just dronekit.

### PR DESCRIPTION
**Pull request by tcr3dr**
This is mostly a documentation / public use issue. Probably should not advise using dronekit.lib directly for any public code.

### CODE REVIEW

**Comment by tcr3dr** [comment]
Note this is rebased over #445, so no merging yet.

**Comment by hamishwillee** [comment]
Excellent. Saved me a job :-)

**Comment by tcr3dr** [comment]
@hamishwillee Gonna close this since I think I have a slightly better idea...

**Comment by hamishwillee** [comment]
@tcr3dr OK. Let me know what it is - the examples are currently stuck between using dronekit and dronekit.lib, and I think this is an unclear story.

**Pull request closed without merging**
