### PR TITLE
Replaces diydrones/dronekit-python with dronekit/dronekit-python.

### PR DESCRIPTION
**Pull request by tcr3dr**
Be wary! This was mostly just find and replace.

### CODE REVIEW

**Comment by mrpollo** [comment]
@tcr3dr `ImportError: No module named numpy` on CircleCI?

**Comment by tcr3dr** [comment]
@mrpollo http://media.giphy.com/media/y65VoOlimZaus/giphy.gif

**Comment by mrpollo** [comment]
lgtm :+1:

**Comment by hamishwillee** [comment]
I've done a basic update of links from the [DroneKit Tutoial](http://dev.ardupilot.com/wiki/droneapi-tutorial/)  and other dev wiki topics too. Note that I'd like to replace this doc since it is superseded, but apparently it is much loved - so I am waiting for people to get used to using the correct documentation.

**Comment by tcr3dr** [comment]
And we should maximize love of developer docs :) Perhaps after we remove the droneapi naming lineage and allow direct running of DK scripts, it will be sufficiently different to warrant a bigger warning.

**Comment by hamishwillee** [comment]
Yes! At that point I will replace the tutorial with an entry point with an overview of what DK is for and links to our new docs.

**Pull request merged**
