### PR TITLE
Logging: use builtin logging module for library and autopilot output

### PR DESCRIPTION
**Pull request by pietrodn**
## Current situation
DroneKit does not play well in the logging department when it's used as a library.
Indeed, the user has no way to configure DroneKit's logging apart from monkey-patching (#862).

The logging of MAVLink `STATUSTEXT` messages can be configured by providing a `status_printer` function to `connect()`; however, while the `STATUSTEXT` message [provides](https://mavlink.io/en/messages/common.html#STATUSTEXT) the severity level ([`MAV_SEVERITY` enum](https://mavlink.io/en/messages/common.html#MAV_SEVERITY)) in a field, DroneKit ignores it and prints all the messages from the autopilot with the same severity.

Also, when an exception is encountered in an attribute or message handler, the stack trace does not get printed, making debugging more difficult.

Related issues: #118, #862

## Proposed changes
This PR tries to improve the situation by replacing all the uses of `errprinter()` and `print()` with the built-in Python [`logging`](https://docs.python.org/3/library/logging.html) module facilities.
The stack trace is printed (`exc_info=True`) in case of "unexpected" exceptions coming from user's code.

`STATUSTEXT` messages are logged by a separate logger to make it clear which messages are coming from the autopilot and which others are emitted from the DroneKit library; the two loggers may be configured independently.
The `STATUSTEXT` messages are printed with the correct logging level specified by the autopilot: filtering by severity is now possible.
The `status_printer` argument of `connect()` is deprecated.

With the proposed changes, the library user would be able to format, filter, redirect and suppress DroneKit's and the autopilot's log messages at his/her pleasure.

## Logging in tests
A nice side effect of this change is that the tests now run completely silent, because nose [captures](https://nose.readthedocs.io/en/latest/plugins/logcapture.html) all the log messages and prints them only in case of error.

To force the printing of log messages in test output, one can do:
```
nosetests -svx --debug=autopilot,dronekit
```

### CODE REVIEW

**Comment by pietrodn** [comment]
In the test output, you may notice that many autopilot logs are at the `CRITICAL` level. This is a bug of ArduPilot [which has already been fixed](https://github.com/ArduPilot/ardupilot/pull/2757). In this PR I decided to respect the MAVLink specification nevertheless.

**Comment by peterbarker** [comment]
I really like the concept.

However, won't the current set of changes here break things for anybody who *is* monkey-patching stuff to clean up the logging?

I mean, we could wave our hands and say "it's master, we're allowed to do that", but given we haven't done a release in... quite some time... that might not be entirely fair.

It would be nice to have some sort of transition arrangement for a year where anybody doing something clever got a warning that errprinter etc was going away.  Can you see a way to do that?

**Comment by pietrodn** [comment]
The current changeset would break all the `errprinter` monkey-patching attempts, in the sense that they would be useless and log messages would be logged to stdout no matter what.

But monkey-patching is a brittle solution anyway, and no one expects libraries not to break when modifying their internals in unexpected ways.

Instead, I think that the biggest retro-compatibility problem is with the `status_printer` argument of the `connect()` function. It allows the user to specify a custom function — accepting a string — to log the *autopilot* (not DroneKit's) messages.
That is a public API and should not break.

In this case, however, we can be smart:
1) if `status_printer` is not specified (default case), we log everything with the new `logging` module: after all, this is what was done before, with print();
2) if `status_printer` is set, we can add a [`Handler`](https://docs.python.org/3/howto/logging.html#handlers) to the autopilot logger, to pass its output through that function, and suppress the default logging to stdout/stderr. DroneKit output would be logged normally (with the logger, to stdout). This strategy should reproduce the current behaviour.

What do you think?

**Comment by hamishwillee** [comment]
@peterbarker FWIW I agree this can reasonably be broken - but we should really make a release to properly document the change (and because it is about time following all recent improvements). Do we have the capacity/ability to make a release or does this require some magic?

**Comment by peterbarker** [comment]
On Sun, 4 Nov 2018, Hamish Willee wrote:

> @peterbarker FWIW I agree this can reasonably be broken - but we should really make a release to properly document the change (and because it is about
> time following all recent improvements). Do we have the capacity/ability to make a release or does this require some magic?

We can make a release happen.

But not on the time scales I'd like to see this change go in :-)

If we can make it compatible, that would be ideal.

**Comment by pietrodn** [comment]
Ok, now the PR does not break the compatibility with old-style `status_printer` arguments via logging handlers.
I also added a test for that.

**Comment by peterbarker** [comment]
Merged, thanks!

"nosetests3" in the root directory yields rather unsatisfactory results, it seems.

**Comment by pietrodn** [comment]
In which sense? This is what I get:

```
(venv)
pietro@ProPietro ~/tmp/dronekit-python
master $ SITL_SPEEDUP=10 nosetests
.............................
----------------------------------------------------------------------
Ran 29 tests in 150.092s

OK
```

**Pull request merged**
