### PR TITLE
Update vehicle_state.py

### PR DESCRIPTION
**Pull request by franknitty69**
vehicle.home_location requires a float, not an integer. changed my_location_alt.alt value from 222 to 222.0

### CODE REVIEW

**Comment by tcr3dr** [comment]
@franknitty69 Thanks for the PR! I'll make sure this passes CI and pull it in.

Would it be useful if the Location{Global,GlobalRelative,Local} objects coerced their attributes into floats when they were assigned? Thus `.alt = 5` would read back as `.alt == 5.0`. This may lead to less user error, though it seems a bit magical.

**Comment by hamishwillee** [comment]
@franknitty69 What was the impact of not doing this? The code ran fine without crashing for me and seemed to work.

**Comment by franknitty69** [comment]
i setup a new vagrant instance and ran the vehicle_state example. it failed with an error on line 69. the error complained about the struct parameter not being a float. when i changed the alt from 222 to 222.0 the error went away. the funny thing is that now if i change it back, i can no longer recreate the error.

**Comment by hamishwillee** [comment]
That is odd. Either way, it should be robust enough to cope. I'm sure @tcr3dr will find some way to make it bullet proof :-)

**Comment by tcr3dr** [comment]
Pulled in by #477!

**Pull request merged**
