### PR TITLE
Gimbal: Added gimbal control

### PR DESCRIPTION
**Pull request by tcr3dr**
Merges #497.

### CODE REVIEW

**Comment by mrpollo** [comment]
looks good to me, are we waiting for @djnugent to include @hamishwillee suggestions?, I'm assuming we can close #497 now

**Comment by djnugent** [comment]
Isn't this missing `@property gimbal()` for the  vehicle object? And this also doesn't deprecate mount_status.

**Comment by hamishwillee** [comment]
Yes @djnugent is correct - missing the gimbal property on vehicle and deprecation of the mount_status. Also I need to add some updates to our other docs.

@mrpollo I'd quite like to know how this was verified/tested and confirmation of my questions. With respect to my suggestions we should minimally support the location types we have as inputs. Deciding to add a body/local frame is another question ....

I'm going to have a play with this now on SITL and will update "the basics".

**Comment by hamishwillee** [comment]
Added a change to:
- add the gimbal property on the vehicle
- make Gimbal not be a HasObservable. This would be useful if we needed to individually observe roll, pitch, yaw, but I don't believe that is the case
- Update reference
- Changed target_gps method to target_location.

Did not:
- Update other docs/guide/examples (still needed)
- Add support for the different types of locations (IMO still needed)

I haven't yet been able to test on simulator due to https://github.com/diydrones/ardupilot/issues/3322 and https://github.com/dronekit/dronekit-sitl/issues/59. 

I did however test on Solo and had some problems. What I observed is that:
- We do get information from the gimbal, and we can observe it and see the value changes.
- When I try to set the position/orientation using ``rotate`` I don't see any movement of the real gimbal. I can see that the value returned by the callback for the set value does change, which makes me thing we may be (incorrectly) caching the value we set - @djnugent  is that possible?
- I attempted to set a ROI. Didn't want to wander too far from my computer so got inconclusive results. I believe that this probably was working ... at least to some extent. I THINK that this can only work in guided mode right - ie it won't work in stabilise mode.

Anyway, @djnugent can you verify that the rotate works OK on Solo for your tests, and ideally supply me the test code/script that verifies this. I'll keep trying to verify on simulator, but unless we look at that value caching problem it will always tell us we succeeded ... so not a "real" test.

**Comment by djnugent** [comment]
Just tested on Solo and it works with this code
```
from dronekit import *
import time

vehicle = connect('0.0.0.0:14550', wait_ready=True)

print "pointing gimbal"
vehicle.gimbal.rotate(-45,0,0)
time.sleep(5)
print "roi"
loc = vehicle.location.global_relative_frame
vehicle.gimbal.target_gps(LocationGlobalRelative(loc.lat,loc.lon,loc.alt -100))
time.sleep(5)
print "releasing control"
vehicle.gimbal.release()
print vehicle.gimbal
time.sleep(0.5)
```

ROI is kind of spotty. After a ran this script a few times it became responsive. But the first few times were delayed. It was odd behavior but definitely an ardupilot thing.

**Comment by djnugent** [comment]
I also confirmed gimbal read back is working. It does not give the actual IMU orientation of the gimbal but the last commanded orientation from the autopilot. This includes ROI, mavlink targeting, and, rc targeting. But it will not change if you poke your gimbal or rotate your copter.

**Comment by hamishwillee** [comment]
HI @djnugent Thanks for that - roi stuff sounds similar to what I was seeing. Particularly useful to know that values are commanded values not measured - I will update docs appropriately. I wasn't seeing movement of the gimbal at all with rotate but I'll try that again. Did you see movement when you tried to set yaw and roll too?

**Comment by hamishwillee** [comment]
@djnugent So I didn't realise the range of the camera pitch is 0 (straight ahead) to -90 (straight down). Pushing it to positive values not working all that well for me!

I tried this with yaw and roll values though, and couldn't see any movement of the gimbal. Did you test this?

**Comment by djnugent** [comment]
Yaw controls solo's heading so I haven't tested that. And I don't think solo gimbal supports roll.

**Comment by hamishwillee** [comment]
You did say that yaw was in global frame - makes sense now. I presume the roll command will just be ignored by the gimbal if not supported? (from what I can see the gimbal floats in the roll axis, so even if the vehicle rolled, the camera would remain level.

**Comment by hamishwillee** [comment]
@djnugent et al. I've updated the documentation for all the methods and the example code. Can you please review the changes and confirm that how I think it works is actually what it does?

I made this so that setting an ROI can take either time of global location. Would be great to set ROIs locally, but too much to do for now. 

There is one more major change we should consider. According to @peterbarker Solo also sends out the GIMBAL_REPORT message, and we should be able to get more information from this - we should at least confirm what it is sending out. 

From a documentation perspective I will also need to add some example code on setting the gimbal, and this requires that I get simulation working. Still working on that (it would not be a blocker to this going out, but I'd hope we'd get the GIMBAL_REPORT looked at.

**Comment by tcr3dr** [comment]
@hamishwillee GIMBAL_REPORT is [here](http://mavlink.org/messages/ardupilotmega#GIMBAL_REPORT):

1. Joint roll / elevation / azimuth (spherical coordinates)
1. Joint vx/vy/vz velocity
1. Joint x/y/z angle
1. Time since last update

Reading through the ardupilot source, it looks like this is too low-level to expose. It's pre-EKF, so the values are less reliable, and it's heartbeat-based from the MAVLink-enabled gimbal rather than from the autopilot. I would be inclined not to expose these in this PR.

So given that, can we merge and open a new issue for enabling the gimbal simulation? Several of us are interested in the simulation bits and testing this is pretty necessary, so I agree we want that soon.

**Comment by hamishwillee** [comment]
@tcr3dr Yes. Essentially the GIMBAL_REPORT is a Solo only feature, so we would consider adding it to SoloVehicle, but not to generic DroneKit-Python. Simulation of gimbals is poor, but I'll add what information there is and post. This should be ready for this to be merged within the next hour.

I do feel that I personally have not tested it as much as I'd like. For example, if doing a yaw normally you can only do it AFTER sending a movement command (you can't just send a yaw during takeoff). Since setting gimbal yaw actually causes the vehicle yaw to change, I'd quite like confirmation that this isn't a limitation on setting gimbal behaviour.

**Comment by hamishwillee** [comment]
@tcr3dr This is IMO ready to merge. Last minor update above points to new section on gimbal simulation I just put into dev wiki: http://dev.ardupilot.com/wiki/using-sitl-for-ardupilot-testing/#adding_a_virtual_gimbal

FYI, 
- this simulation is very poor (just about to create a defect report). Essentially it does allow you to start getting MOUNT_STATUS messages but our commands from dronekit (and mission planner) appear to be ignored. Specifically on Solo you send a yaw command then the vehicle yaws - but on simulator nothing happens. I think GIMBAL_REPORT is too high level, but it would be nice to know that the "intention" of the command had actually been followed :-0
- Gimbal simulation breaks Native windows/Cygwin and DK-SITL. @peterbarker has very kindly worked out a fix for vagrant-based SITL.

ANyway, good to merge!

**Comment by tcr3dr** [comment]
@hamishwillee Loud and clear. @wsilva32 you might be interested in the above information on SITL's compatibility with gimbal right now.

**Comment by hamishwillee** [comment]
Thank you. @wsilva32 FYI, these are some of the issues on the topic of simulation https://github.com/diydrones/ardupilot/issues/3335 , https://github.com/dronekit/dronekit-sitl/issues/59 , https://github.com/diydrones/ardupilot/issues/3322 , https://github.com/diydrones/ardupilot/pull/3325

**Pull request merged**
