### PR TITLE
v1.5.0

### PR DESCRIPTION
**Pull request by tcr3dr**

### CODE REVIEW

**Comment by hamishwillee** [comment]
@tcr3dr The documentation now reflects 1.5 but the [latest PIP is 1.4.2](http://pypi-ranking.info/module/droneapi#release_history) and the latest windows dk release installer is ... also 1.4.2. Which tells me that the rebuild yesterday didn't quite work either (or that it did, but it didn't create the "latest" installer file).

**Comment by tcr3dr** [comment]
@hamishwillee Latest Pypi is 1.5.0 https://pypi.python.org/pypi/droneapi so I'm not sure what's going on with the ranking.

Re: Windows: Augh.

**Comment by tcr3dr** [comment]
Thanks for double checking all this :)

**Comment by hamishwillee** [comment]
@tcr3dr You're welcome. Just tested windows ["latest" link again](https://s3.amazonaws.com/dronekit-installers/windows/dronekit-windows-latest.exe) - got "no such bucket error. I presume that means you're working on it?

**Comment by hamishwillee** [comment]
But on the positive side, the latest version is on PIP and works as advertised. Thank you!

**Comment by tcr3dr** [comment]
@hamishwillee Oh gosh, it's been the wrong URL this whole time. https://s3.amazonaws.com/dronekit-assets/installers/dronekit-windows-latest.exe

**Comment by hamishwillee** [comment]
Well, it worked before and works (right) now. Does it need to change?

**Pull request merged**
