### PR TITLE
Upgrade CircleCI configuration to version 2.0

### PR DESCRIPTION
**Pull request by pietrodn**
This PR introduces CircleCI 2.0 support while deprecating CircleCI 1.0.

The reasons for this change are the following:
- [CircleCI 1.0 will reach End Of Life on August 31, 2018](https://circleci.com/blog/sunsetting-1-0/)
- Clearer environment definition thanks to Docker images
- Parallel Python 2 and Python 3 builds thanks to [workflows](https://circleci.com/docs/2.0/workflows/)

Currently this configuration [builds successfully](https://circleci.com/gh/pietrodn/dronekit-python/tree/circle2) using Python 2 on my CircleCI account.
The Python 3 build fails in the testing phase, [as expected](https://github.com/ArduPilot/pymavlink/pull/141).

I don't have the SSH keys for deployment so I cannot check if the deploy step is executed correctly. However, I [checked](https://circleci.com/gh/pietrodn/dronekit-python/21) that it attempts the deploy only on the correct branch specified by the filter.

Gitter notifications are working, as before.

### CODE REVIEW

**Comment by hamishwillee** [comment]
Awesome. Thank you. @peterbarker Do you have the keys or is this one for Ramon? If so, he is away for a couple of weeks.

**Comment by peterbarker** [comment]
On Tue, 27 Mar 2018, Hamish Willee wrote:

> Awesome. Thank you. @peterbarker Do you have the keys or is this one for

I don't have the keys.  Should probably fix that.

**Comment by hamishwillee** [comment]
Thanks @peterbarker I agree. Can you chase @mrpollo ?

**Comment by mrpollo** [comment]
The build fail is preventing CircleCI to reach the "deploy" state, @pietrodn can you please comment out the python3 step in the config? we can bring it back once **pymavlink** changes go in. Thanks for the update to the config file 👍

**Comment by mrpollo** [comment]
Yes, its because we are using parallelism, read the following warning from the docs:

https://circleci.com/docs/2.0/configuration-reference/#deploy

>In general deploy step behaves just like run with one exception - in a job with parallelism, the deploy step will only be executed by node #0 and only if all nodes succeed. Nodes other than #0 will skip this step.

**Comment by pietrodn** [comment]
Oh, I didn't know that. Now it's corrected! :-)

**Comment by mrpollo** [comment]
Not sure why but the deploy step is still not triggering...

**Comment by mrpollo** [comment]
Actually I know why... it would only deploy if the CI was running against master, which will happen now that I triggered the squash/merge of this pr.

Follow build here https://circleci.com/workflow-run/7ce7614c-7368-4f61-8db9-e622a090665c

**Comment by pietrodn** [comment]
Thank you :) Finally CircleCI is working!

**Pull request merged**
