### PR TITLE
Add visual studio project file

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by hamishwillee** [comment]
@peterbarker Do you use VS? Ie can you test this?

**Comment by peterbarker** [comment]
On Wed, 19 Apr 2017, Hamish Willee wrote:

> @peterbarker Do you use VS? Ie can you test this?

I'll try not to be *too* insulted by that question, Hamish ;-)

**Comment by hamishwillee** [comment]
Ha! Its just that I don't have VS set up right now, and I don't use it for Python dev.

**Comment by mrpollo** [comment]
my only concern is vs project files contain references to files and those might change thus making this file outdated, i think its too hard to maintain it, perhaps just keep the ignore file?

**Comment by amilcarlucas** [comment]
Good point,‎ I will redo the PR
 
 
 
 Gesendet von meinem BlackBerry 10-Smartphone.
 
 Mit freundlichen Grüßen,
 
 Amilcar Lucas
 
 Software and Algorithms, MD-M1
 Business Area Powertrain Mechatronics Diesel
 
 IAV GmbH 
 Nordhoffstraße 5
 38518 GIFHORN
 GERMANY
 
 Tel.: +49 5371 805-3393
 Mob: +49 162 1075513
 Fax: +49 5371 805-1789
 
 E-mail: <mailto:amilcar.lucas@iav.de>
 Internet: http://www.iav.com
 
 Sitz/Registered Office: Berlin, 
 Registergericht/Registration Court: Amtsgericht Charlottenburg, 
 Registernummer/Company Registration Number: HRB 21 280, 
 Geschäftsführer/Managing Directors: Kurt Blumenröder, Michael Schubert, Kai-Stefan Linnenkohl
 Vorsitzender des Aufsichtsrates/Chairman of the Supervisory Board: Prof. Dr. Harald Ludanek
 
 
   
 
   Von: Ramon Roche
    Gesendet: Freitag, 21. April 2017 19:55
    An: dronekit/dronekit-python
    Antwort an: dronekit/dronekit-python
    Cc: Amilcar Lucas; Author
    Betreff: [RMX:#] Re: [dronekit/dronekit-python] Add visual studio project file (#706)
 
 my only concern is vs project files contain references to files and those might change thus making this file outdated, i think its too hard to maintain it, perhaps just keep the ignore file?

**Pull request closed without merging**
