### PR TITLE
fixed Unknown Endpoint message

### PR DESCRIPTION
**Pull request by mwieder**
one piddly typo fixed.

### CODE REVIEW

**Comment by mwieder** [comment]
Well, that's interesting. Is the DRONEAPI_KEY env variable not set up for CircleCI? I see that exporting it from the circle.yml file is suppressed.

**Comment by hamishwillee** [comment]
@tcr3dr No reason not to accept this fix. Thank @mwieder.

**Comment by tcr3dr** [comment]
@mwieder I'm going to pull this commit in on a separate PR (since the tests require privileged access to pass which I'd like to fix sometime), but thank you and will merge shortly!

**Comment by tcr3dr** [comment]
Merged by #486.

**Pull request closed without merging**
