### PR TITLE
bump to 2.4.0

### LINKED ISSUE #597: New build of docs please
The published docs do not match the version on master - see https://github.com/dronekit/dronekit-python/blob/master/docs/examples/simple_goto.rst and http://python.dronekit.io/examples/simple_goto.html

### PR DESCRIPTION
**Pull request by mrpollo**
- included all the version changes and release notes
- also added some logic to auto publish the docs after successful travis run on master branch (currently only possible after a PR has been merged) this fixes #597

### CODE REVIEW

**Comment by mrpollo** [comment]
cc @hamishwillee can you review release notes?

**Comment by hamishwillee** [comment]
@mrpollo I fixed a couple of typos, but otherwise this looks good. Excellent that autopublish now fixed - THANKS!

**Comment by peterbarker** [comment]
Looks good.

**Comment by hamishwillee** [comment]
@mrpollo So we think you can self-merge when you're ready to release :-)

**Comment by mrpollo** [comment]
as soon as travis is happy, not sure why it hasn't started building yet

**Comment by peterbarker** [comment]
... because we're tired of waiting for this circle to go green.

**Comment by hamishwillee** [comment]
@peterbarker If there was a like button on your last post above I
d have pushed it :-)

**Comment by mrpollo** [comment]
@hamishwillee going to move the travis auto-docs commit to a new PR given its creating some conflict with travis...

**Pull request merged**
