### PR TITLE
Drone delivery home

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by hamishwillee** [comment]
@peterbarker Let me know when your usage instructions are done and I'll test this and them together.

**Comment by peterbarker** [comment]
Plan B.  Separate PR for the Vagrant stuff.

**Comment by hamishwillee** [comment]
Separating this out is good thanks. As per other one:

* I don't see running examples in Vagrant as particularly useful, but not opposed.
* I'll merge once the howto is written. Suggest wiki for that.

**Comment by hamishwillee** [comment]
Yes, works as advertised. Thanks!

**Pull request merged**
