### PR TITLE
Integrates local-position class.

### PR DESCRIPTION
**Pull request by tcr3dr**

### CODE REVIEW

**Comment by mrpollo** [comment]
so long and takes for all the fish `Location` class

**Comment by hamishwillee** [comment]
Lovely. I've added label for "needs docs". You've done a great job on the ref, but this probably needs something in the guide too. I'll look at that once this is merged.

**Comment by squilter** [comment]
@tcr3dr Any updates?  I am working on a project that relies on this feature, and I was hoping that this could be useable before next Sunday. (via the pip version)

**Comment by tcr3dr** [comment]
@squilter My bad. Let me get this merged ASAP.

One more note to self: re-export Location class for back-compat, removal by final release.

**Comment by hamishwillee** [comment]
@tcr3dr This looks nice for returning the local position. Can `vehicle.commands.goto()` take a local position?

If not, I'd suggest that we merge this and add a second update to allow movement control using local positioning. That requires a little more thinking - since in Copter 3.3 you can use frames which allow you to specify that the NED values are relative to home position or the vehicle axes (ie "North" maps to the direction that the front of the vehicle is pointing) but in Copter 3.2.1 all values are "pure NED". 

Docs on the movement/frames are at the [end of this section in wiki](http://dev.ardupilot.com/wiki/copter-commands-in-guided-mode/#set_position_target_local_ned).

**Comment by squilter** [comment]
@tcr3dr Thanks!

**Comment by tcr3dr** [comment]
@squilter published! https://github.com/dronekit/dronekit-python/commit/c2852171738e3ab5d999c31b64180949a506f76f

**Comment by squilter** [comment]
:smiley:

**Comment by uavfans** [comment]
how to use ,any documents?

**Comment by hamishwillee** [comment]
Api reference in place. Guide docs and example update planned for Tuesday.

**Comment by uavfans** [comment]
Linux computer connected to the vehicle via USB	mavproxy.py --master=/dev/ttyUSB0
Linux computer connected to the vehicle via Serial port (RaspberryPi example)	mavproxy.py --master=/dev/ttyAMA0 --baudrate 57600
SITL connected to the vehicle via UDP	mavproxy.py --master=127.0.0.1:14550
OSX computer connected to the vehicle via USB	mavproxy.py --master=/dev/cu.usbmodem1
Windows computer connected to the vehicle via USB	mavproxy.py --master=/dev/cu.usbmodem1

there is error  about Windows computer connected to the vehicle via USB	mavproxy.py --master=/dev/cu.usbmodem1

**Comment by uavfans** [comment]
In document getting started

**Comment by hamishwillee** [comment]
@uavfans Thanks. I thought I fixed that. I'll make sure fix goes in next PR.

**Pull request merged**
