### PR TITLE
Restructured DroneKit Documentation

### PR DESCRIPTION
**Pull request by hamishwillee**
This restructures the DroneKit documentation with a much simpler quickstart (replacing the old getting started) with very minimalist  installation instructions and a script that they can copy-paste to set up dronekit-sitl and run (ie zero configuration).

I split out a new section "Developing with DroneKit" which covers installation (cut down topic), simulation, companion computers, coding standards. Still to do in this are "best practise" and updating Simulation topic to use DK-Sitl.

The guide is now pure "how to use the API". This starts with a separate "Connection" topic. This is OK, but I will update that connection topic further in a later revision (this is much easier to do now it is a stand-alone topic).

All links have been fixed up.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@mrpollo This can be merged if you want, but worth waiting on best practises and my simulation topic.

**Comment by hamishwillee** [comment]
@mrpollo @tcr3dr This now has new best practice section.

I think it should be merged. 

We do still need to update the simulator section, which I hope to do tomorrow. If you don't merge I'll probably tack those changes on top of this.

**Comment by zlite** [comment]
Bravo! When will this go live?

This restructures the DroneKit documentation with a much simpler quickstart
(replacing the old getting started) with very minimalist installation
instructions and a script that they can copy-paste to set up dronekit-sitl
and run (ie zero configuration).

I split out a new section "Developing with DroneKit" which covers
installation (cut down topic), simulation, companion computers, coding
standards. Still to do in this are "best practise" and updating Simulation
topic to use DK-Sitl.

The guide is now pure "how to use the API". This starts with a separate
"Connection" topic. This is OK, but I will update that connection topic
further in a later revision (this is much easier to do now it is a
stand-alone topic).

All links have been fixed up.
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/dronekit/dronekit-python/pull/505
Commit Summary

   - Move topics into new folders (breaks index, will repair later)
   - Migrate to new structure and fix up links. Omits best-practise guide

File Changes

   - *M* docs/about/index.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-0> (1)
   - *R* docs/about/migrating.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-1> (2)
   - *M* docs/contributing/developer_setup_linux.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-2> (3)
   - *M* docs/contributing/developer_setup_windows.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-3> (2)
   - *A* docs/develop/coding_standards.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-4> (14)
   - *R* docs/develop/companion-computers.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-5> (0)
   - *A* docs/develop/index.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-6> (23)
   - *A* docs/develop/installation.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-7> (35)
   - *R* docs/develop/sitl_setup.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-8> (0)
   - *M* docs/examples/channel_overrides.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-9> (2)
   - *M* docs/examples/create_attribute.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-10> (2)
   - *M* docs/examples/drone_delivery.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-11> (2)
   - *M* docs/examples/flight_replay.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-12> (2)
   - *M* docs/examples/follow_me.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-13> (2)
   - *M* docs/examples/guided-set-speed-yaw-demo.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-14> (4)
   - *M* docs/examples/mission_basic.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-15> (2)
   - *M* docs/examples/mission_import_export.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-16> (2)
   - *M* docs/examples/simple_goto.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-17> (2)
   - *M* docs/examples/vehicle_state.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-18> (2)
   - *A* docs/guide/connecting_vehicle.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-19>
   (63)
   - *D* docs/guide/getting_started.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-20>
   (183)
   - *M* docs/guide/index.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-21> (9)
   - *A* docs/guide/quick_start.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-22>
   (119)
   - *M* docs/guide/taking_off.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-23>
   (19)
   - *M* docs/index.rst
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-24>
   (10)
   - *M* examples/simple_goto/simple_goto.py
   <https://github.com/dronekit/dronekit-python/pull/505/files#diff-25> (3)

Patch Links:

   - https://github.com/dronekit/dronekit-python/pull/505.patch
   - https://github.com/dronekit/dronekit-python/pull/505.diff

—
Reply to this email directly or view it on GitHub
<https://github.com/dronekit/dronekit-python/pull/505>.

**Comment by mrpollo** [comment]
lgtm! :+1:  great work @hamishwillee

**Comment by mrpollo** [comment]
just went live @zlite http://python.dronekit.io/guide/quick_start.html

**Pull request merged**
